from __future__ import annotations

import keyword


SYNTAX_SCHEMES = {
    ".py": {
        "name": "Python",
        "keywords": set(keyword.kwlist),
        "comment": r"#.*$",
        "string": r"('([^'\\]|\\.)*'|\"([^\"\\]|\\.)*\"|'''[\s\S]*?'''|\"\"\"[\s\S]*?\"\"\")",
        "number": r"\b\d+(?:\.\d+)?\b",
    },
    ".html": {
        "name": "HTML",
        "keywords": {
            "html",
            "head",
            "body",
            "div",
            "span",
            "script",
            "style",
            "title",
            "meta",
            "link",
            "main",
            "section",
            "article",
            "header",
            "footer",
            "nav",
            "button",
            "form",
            "input",
            "label",
            "h1",
            "h2",
            "h3",
            "p",
            "a",
            "img",
            "ul",
            "li",
        },
        "comment": r"<!--[\s\S]*?-->",
        "string": r"('([^'\\]|\\.)*'|\"([^\"\\]|\\.)*\")",
        "number": r"\b\d+(?:\.\d+)?\b",
    },
    ".htm": {
        "name": "HTML",
        "keywords": {
            "html",
            "head",
            "body",
            "div",
            "span",
            "script",
            "style",
            "title",
            "meta",
            "link",
        },
        "comment": r"<!--[\s\S]*?-->",
        "string": r"('([^'\\]|\\.)*'|\"([^\"\\]|\\.)*\")",
        "number": r"\b\d+(?:\.\d+)?\b",
    },
    ".css": {
        "name": "CSS",
        "keywords": {
            "color",
            "background",
            "display",
            "position",
            "padding",
            "margin",
            "font",
            "border",
            "grid",
            "flex",
            "width",
            "height",
        },
        "comment": r"/\*[\s\S]*?\*/",
        "string": r"('([^'\\]|\\.)*'|\"([^\"\\]|\\.)*\")",
        "number": r"\b\d+(?:\.\d+)?(?:px|rem|em|%)?\b",
    },
    ".js": {
        "name": "JavaScript",
        "keywords": {
            "function",
            "return",
            "const",
            "let",
            "var",
            "if",
            "else",
            "for",
            "while",
            "class",
            "import",
            "export",
            "new",
            "async",
            "await",
        },
        "comment": r"//.*$|/\*[\s\S]*?\*/",
        "string": r"('([^'\\]|\\.)*'|\"([^\"\\]|\\.)*\"|`([^`\\]|\\.)*`)",
        "number": r"\b\d+(?:\.\d+)?\b",
    },
    ".json": {
        "name": "JSON",
        "keywords": {"true", "false", "null"},
        "comment": None,
        "string": r"\"([^\"\\]|\\.)*\"",
        "number": r"\b\d+(?:\.\d+)?\b",
    },
    ".md": {
        "name": "Markdown",
        "keywords": set(),
        "comment": None,
        "string": r"`[^`]*`",
        "number": None,
    },
}

SYNTAX_MENU_OPTIONS = [
    ("Plain Text", None),
    ("Python", ".py"),
    ("HTML", ".html"),
    ("CSS", ".css"),
    ("JavaScript", ".js"),
    ("JSON", ".json"),
    ("Markdown", ".md"),
]
